### PR TITLE
fix(bug): typo, dependencies -1 bug, api changes, text-overflow problem

### LINKED ISSUE #244: Typo in work item screen after creating work items from recommender
Steps to reproduce:

1. Login to openshift
2. Create a new space
3. Use the starter application and create a starter project (say Vert.x basic)
4. Go to pipelines tab
5. Trigger a pipeline build for the one that you have created.
6. Stack analysis report link will show up (Else log an issue in this repo for the same)
7. Click on stack analysis link (A modal will show up)
8. Click on create work item if any
9. Go to the view work item link
10. Check the typo in the description (It has to be potential version upgrade instead of 'potentially')
screen shot 2017-06-09 at 11 36 52 am

### PR DESCRIPTION
**Pull request by arunkumars08**
Changes the Stack API utils file to expose more data so it can be consumed from across. 
Corrects the typo from potentially to potential
Corrects the bug for dependencies' code metrics count -1, -2 to NA
Corrects the text overflow problem in the dependencies table.

Fixes #244 #257 #249

### CODE REVIEW

**Comment by joshuawilson** [comment]
While it may be easier to do a lot of things at once, it is a lot riskier to do it this way. Please do one thing per commit/PR. When the build works, this goes to production. 
Consider this, if something is wrong in this and we revert you lose all the changes. I have done that several times and the dev has to recover the parts that do work.

**Comment by miteshvp** [comment]
We still need to correct https://github.com/fabric8-ui/fabric8-recommender/blob/226e4dfd649da6d7b4fb7f4e9f403409f6cb8fc6/src/app/stack/stack-details/stack-details.component.ts#L195

**Comment by miteshvp** [comment]
I guess https://github.com/fabric8-ui/fabric8-recommender/pull/260 handles that

**Comment by arunkumars08** [comment]
@miteshvp Ya, I accidentally missed that one. #260 should handle that

**Pull request merged**
