### PR TITLE
Fix component feedback

### PR DESCRIPTION
**Pull request by invincibleJai**
- Fixes issue with the header not being set for component feedback API
- Removes unneeded imports

Tracks : https://github.com/openshiftio/openshift.io/issues/4363

### CODE REVIEW

**Comment by sbose78** [comment]
Wasn't there a common http client where we setting the header if the request was being sent to a *.openshift.io URL ?

**Comment by invincibleJai** [comment]
@sbose78 if am not wrong,  discussion happend on platform channel and conclusion was lib's in fabric8-ui will continue sending headers as it's now without relying on interceptors. as in 

`
this.headers = this.headers.set('Authorization', 'Bearer ' + this.auth.getToken());
`

the reason it failed for `component-feedback` is `HttpHeaders` is immutable so can't be set directly later.

I am not ware if there is any common custom http-client is there and can be used.

**Comment by sbose78** [comment]
@invincibleJai :+1: Wasn't aware of the discussion.

**Comment by corinnekrych** [comment]
@invincibleJai indeed some issue with Demo app, see my comment: https://github.com/invincibleJai/fabric8-recommender/pull/10

**Comment by invincibleJai** [comment]
thanks @corinnekrych , let me try it out

**Comment by invincibleJai** [comment]
Demo app needs to be looked into, lib is fine.

**Pull request merged**
