### PR TITLE
Changes the style and feel of the feature.

### PR DESCRIPTION
**Pull request by arunkumars08**
What this commit does?

1. Changes in the style to make it in sync with the UX.
2. Removed unnecessary code.
3. Added a few classes to achieve styles.

Tracks #6.

### CODE REVIEW

**Comment by arunkumars08** [comment]
@humaton This can be merged.

**Comment by arunkumars08** [comment]
@humaton Could you review this file?

https://github.com/arunkumars08/fabric8-recommender/blob/8e23435a5182bbe8d1419f9f16c7b75a2ffa00a4/src/app/analyze/stack/overview/chart-component.ts

This acts as a wrapper for consuming c3 charts easily in angular2 applications.

**Comment by humaton** [comment]
Do we really need to introduce c3 as dependency?

**Comment by arunkumars08** [comment]
@humaton For charts, I think that will be easier when we opt for C3. Given that patternfly doesn't yet support Angular2, I think this should be ok to go ahead with C3.

**Comment by humaton** [comment]
Well my opinion is different here every dependency that we don't need is a bad dependency.

**Comment by arunkumars08** [comment]
I understand. But something we have to include for charts right? How can we
go about then?

**Pull request merged**
