### PR TITLE
Call stack analysis service only after click of button

### LINKED ISSUE #102: Call stack analysis service only after click of button
Please look into this

### PR DESCRIPTION
**Pull request by invincibleJai**
fixes #102

### CODE REVIEW

**Comment by invincibleJai** [comment]
@arunkumars08 pls review

**Comment by joshuawilson** [comment]
@invincibleJai you know if you don't use the correct syntax in the commit, the change isn't released.

**Comment by arunkumars08** [comment]
@joshuawilson Yes Joshua. I deliberately wanted him to commit that way. I have a few bunch of things I will be pushing anyway so wanted to take everything as one release. That's the reason.

**Comment by joshuawilson** [comment]
works for me, just making sure that everyone know how the system works :)

**Pull request merged**
