### PR TITLE
removed stack-overview folder i.e accordion and related dependencies

### PR DESCRIPTION
**Pull request by invincibleJai**
removed stack-overview folder i.e the accordion and just having one btn and code refactored

### CODE REVIEW

**Comment by invincibleJai** [comment]
@humaton Do not merge now as needs to be tested with actual API response

**Comment by humaton** [comment]
What about tests are they passing?

**Comment by invincibleJai** [comment]
yes all tests have passed

**Comment by invincibleJai** [comment]
@humaton this can be merged.

**Comment by humaton** [comment]
can you rebase it please?

**Comment by invincibleJai** [comment]
@humaton resolved

**Comment by arunkumars08** [comment]
@humaton Please don't merge this.

**Comment by invincibleJai** [comment]
@arunkumars08 fixed failing test case , pls confirm . It can be merged then

**Comment by arunkumars08** [comment]
@humaton Verified and things are working fine. This can be merged now.
@invincibleJai  things are fine.

**Pull request merged**
