### PR TITLE
Adapt script to run ci centos tests

### PR DESCRIPTION
**Pull request by hectorj2f**
ping @naina-verma

### CODE REVIEW

**Comment by hectorj2f** [comment]
related to https://github.com/almighty/almighty-jobs/pull/194

**Comment by naina-verma** [comment]
Hi @hectorj2f,
you pr LGTM, can you please check https://github.com/fabric8-ui/fabric8-recommender/pull/238 PR, In #238 it triggers the Jenkin's job .

**Comment by arunkumars08** [comment]
@hectorj2f Could you rebase and push the changes? it is out of sync.

**Comment by hectorj2f** [comment]
@arunkumars08 @naina-verma can you merge this PR :) ?

**Pull request merged**
